package com.paperpad.mybox.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Generated;

@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
	"active_languages",
	"image_header_link",
	"couleur_fond_general",
	"couleur_barre_navigation",
	"couleur_fond_product",
	"couleur_title_product",
	"currency",
	"lattitude",
	"longitude",
	"url_web_console",
	"email_contact",
	"presentation_console",
	"lien_image_presentation_console"
})
public class Console {

	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	
	@ForeignCollectionField(eager = true)
	private Collection<LanguageString> active_languages2 = new ArrayList<LanguageString>();
	
	@JsonProperty("active_languages")
	private List<String> active_languages = new ArrayList<String>();
	
	@DatabaseField(canBeNull = true)
	private Integer last_update;
	
	@DatabaseField(canBeNull = true, dataType = DataType.STRING)
	@JsonProperty("image_header_link")
	private String image_header_link;
	
	@DatabaseField(canBeNull = true, dataType = DataType.STRING)
	@JsonProperty("couleur_fond_general")
	private String couleur_fond_general;
	
	@DatabaseField(canBeNull = true, dataType = DataType.STRING)
	@JsonProperty("couleur_barre_navigation")
	private String couleur_barre_navigation;
	
	@DatabaseField(canBeNull = true, dataType = DataType.STRING)
	@JsonProperty("couleur_fond_product")
	private String couleur_fond_product;
	
	@DatabaseField(canBeNull = true, dataType = DataType.STRING)
	@JsonProperty("couleur_title_product")
	private String couleur_title_product;
	
	@DatabaseField(canBeNull = true, dataType = DataType.STRING)
	@JsonProperty("currency")
	private String currency;
	
	@DatabaseField(canBeNull = true, dataType = DataType.DOUBLE_OBJ)
	@JsonProperty("lattitude")
	private Double lattitude;
	
	@DatabaseField(canBeNull = true, dataType = DataType.DOUBLE_OBJ)
	@JsonProperty("longitude")
	private Double longitude;
	
	@DatabaseField(canBeNull = true, dataType = DataType.STRING)
	@JsonProperty("url_web_console")
	private String url_web_console;
	
	@DatabaseField(canBeNull = true, dataType = DataType.STRING)
	@JsonProperty("email_contact")
	private String email_contact;
	
	@DatabaseField(canBeNull = true, dataType = DataType.STRING)
	@JsonProperty("presentation_console")
	private String presentation_console;
	
	@DatabaseField(canBeNull = true, dataType = DataType.STRING)
	@JsonProperty("lien_image_presentation_console")
	private String lien_image_presentation_console;
	
	private Map<String, Object> additionalProperties = new HashMap<String, Object>();

	@JsonProperty("active_languages")
	public List<String> getActive_languages() {
		return active_languages;
	}

	@JsonProperty("active_languages")
	public void setActive_languages(List<String> active_languages) {
		this.active_languages = active_languages;
	}

	@JsonProperty("image_header_link")
	public String getImage_header_link() {
		return image_header_link;
	}

	@JsonProperty("image_header_link")
	public void setImage_header_link(String image_header_link) {
		this.image_header_link = image_header_link;
	}

	@JsonProperty("couleur_fond_general")
	public String getCouleur_fond_general() {
		return couleur_fond_general;
	}

	@JsonProperty("couleur_fond_general")
	public void setCouleur_fond_general(String couleur_fond_general) {
		this.couleur_fond_general = couleur_fond_general;
	}

	@JsonProperty("couleur_barre_navigation")
	public String getCouleur_barre_navigation() {
		return couleur_barre_navigation;
	}

	@JsonProperty("couleur_barre_navigation")
	public void setCouleur_barre_navigation(String couleur_barre_navigation) {
		this.couleur_barre_navigation = couleur_barre_navigation;
	}

	@JsonProperty("couleur_fond_product")
	public String getCouleur_fond_product() {
		return couleur_fond_product;
	}

	@JsonProperty("couleur_fond_product")
	public void setCouleur_fond_product(String couleur_fond_product) {
		this.couleur_fond_product = couleur_fond_product;
	}

	@JsonProperty("couleur_title_product")
	public String getCouleur_title_product() {
		return couleur_title_product;
	}

	@JsonProperty("couleur_title_product")
	public void setCouleur_title_product(String couleur_title_product) {
		this.couleur_title_product = couleur_title_product;
	}

	@JsonProperty("currency")
	public String getCurrency() {
		return currency;
	}

	@JsonProperty("currency")
	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@JsonProperty("lattitude")
	public Double getLattitude() {
		return lattitude;
	}

	@JsonProperty("lattitude")
	public void setLattitude(Double lattitude) {
		this.lattitude = lattitude;
	}

	@JsonProperty("longitude")
	public Double getLongitude() {
		return longitude;
	}

	@JsonProperty("longitude")
	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@JsonProperty("url_web_console")
	public String getUrl_web_console() {
		return url_web_console;
	}

	@JsonProperty("url_web_console")
	public void setUrl_web_console(String url_web_console) {
		this.url_web_console = url_web_console;
	}

	@JsonProperty("email_contact")
	public String getEmail_contact() {
		return email_contact;
	}

	@JsonProperty("email_contact")
	public void setEmail_contact(String email_contact) {
		this.email_contact = email_contact;
	}

	@JsonProperty("presentation_console")
	public String getPresentation_console() {
		return presentation_console;
	}

	@JsonProperty("presentation_console")
	public void setPresentation_console(String presentation_console) {
		this.presentation_console = presentation_console;
	}

	@JsonProperty("lien_image_presentation_console")
	public String getLien_image_presentation_console() {
		return lien_image_presentation_console;
	}

	@JsonProperty("lien_image_presentation_console")
	public void setLien_image_presentation_console(String lien_image_presentation_console) {
		this.lien_image_presentation_console = lien_image_presentation_console;
	}

	@JsonAnyGetter
	public Map<String, Object> getAdditionalProperties() {
		return this.additionalProperties;
	}

	@JsonAnySetter
	public void setAdditionalProperties(String name, Object value) {
		this.additionalProperties.put(name, value);
	}

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the active_languages2
	 */
	public Collection<LanguageString> getActive_languages2() {
		return active_languages2;
	}

	/**
	 * @param active_languages2 the active_languages2 to set
	 */
	public void setActive_languages2(Collection<LanguageString> active_languages2) {
		this.active_languages2 = active_languages2;
	}

	/**
	 * @return the last_update
	 */
	public Integer getLast_update() {
		return last_update;
	}

	/**
	 * @param last_update the last_update to set
	 */
	public void setLast_update(Integer last_update) {
		this.last_update = last_update;
	}

	public Console() {
		super();
		// TODO Auto-generated constructor stub
	}

}