package com.paperpad.mybox.models;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "ids_coffret")
public class IdCoffret {
	// id is generated by the database and set on the object automagically
		@DatabaseField(generatedId = true)
		int id;
		
		@DatabaseField(foreign= true, foreignAutoRefresh=true)
		private CategoriesGetter categoriesGetter;
		
		@DatabaseField(canBeNull = false)
		private Integer id_coffret;

		/**
		 * @return the id
		 */
		public int getId() {
			return id;
		}

		/**
		 * @param id the id to set
		 */
		public void setId(int id) {
			this.id = id;
		}

		/**
		 * @return the id_coffret
		 */
		public Integer getId_coffret() {
			return id_coffret;
		}

		/**
		 * @param id_coffret the id_coffret to set
		 */
		public void setId_coffret(Integer id_coffret) {
			this.id_coffret = id_coffret;
		}

		public IdCoffret(Integer id_coffret) {
			super();
			this.id_coffret = id_coffret;
		}

		/**
		 * @return the categoriesGetter
		 */
		public CategoriesGetter getCategoriesGetter() {
			return categoriesGetter;
		}

		/**
		 * @param categoriesGetter the categoriesGetter to set
		 */
		public void setCategoriesGetter(CategoriesGetter categoriesGetter) {
			this.categoriesGetter = categoriesGetter;
		}

		public IdCoffret() {
			super();
			// TODO Auto-generated constructor stub
		}

}
